#!/usr/bin/env bash
set -euo pipefail

export CLAUDE_CONFIG_DIR="${CLAUDE_CONFIG_DIR:-/app/config}"
export MYRIDIUS_CLI_AGENT="${MYRIDIUS_CLI_AGENT:-backend-specialist}"
export MYRIDIUS_CLI_FULL_AUTO="${MYRIDIUS_CLI_FULL_AUTO:-1}"
export MYRIDIUS_CLI_PERMISSION_MODE="${MYRIDIUS_CLI_PERMISSION_MODE:-}"
export MYRIDIUS_CLI_ALLOW_ROOT_BYPASS="${MYRIDIUS_CLI_ALLOW_ROOT_BYPASS:-1}"
export MYRIDIUS_CLI_DANGEROUSLY_SKIP_PERMISSIONS="${MYRIDIUS_CLI_DANGEROUSLY_SKIP_PERMISSIONS:-0}"
export MYRIDIUS_CLI_STREAM_LINE_LOGS="${MYRIDIUS_CLI_STREAM_LINE_LOGS:-1}"
export MYRIDIUS_CLI_OUTPUT_FORMAT="${MYRIDIUS_CLI_OUTPUT_FORMAT:-stream-json}"
export MYRIDIUS_CLI_VERBOSE="${MYRIDIUS_CLI_VERBOSE:-1}"

node /app/worker.js



