/**
 * Gitignore Manager
 * Ensures .gitignore is configured to exclude test results and build artifacts
 */

import { readFile, writeFile, access } from 'fs/promises';
import { join } from 'path';

const MAVEN_GITIGNORE_PATTERNS = `
# Maven Build Outputs - Test Results and Coverage
# Generated by Maven/JaCoCo - should NOT be committed
# Test results are parsed and included in PR description only

# Maven target directory
target/

# JaCoCo Coverage Reports
*.exec
jacoco.xml
**/jacoco/
**/site/jacoco/

# Surefire/Failsafe Test Reports
**/surefire-reports/
**/failsafe-reports/
TEST-*.xml

# Build artifacts
*.class
*.jar
*.war
*.ear
*.log

# IDE files
.idea/
*.iml
.vscode/
*.swp
*.swo
*~

# OS files
.DS_Store
Thumbs.db
`;

/**
 * Ensure .gitignore has Maven build patterns
 * @param {string} workspacePath - Path to repository workspace
 * @param {object} logger - Logger instance
 * @returns {Promise<boolean>} True if .gitignore was updated
 */
export async function ensureMavenGitignore(workspacePath, logger = console) {
  const gitignorePath = join(workspacePath, '.gitignore');

  try {
    // Check if .gitignore exists
    let existingContent = '';
    let gitignoreExists = false;

    try {
      await access(gitignorePath);
      existingContent = await readFile(gitignorePath, 'utf-8');
      gitignoreExists = true;
    } catch (error) {
      // .gitignore doesn't exist, will create it
    }

    // Check if Maven patterns are already present
    if (existingContent.includes('target/') && existingContent.includes('surefire-reports/')) {
      logger.log('✓ .gitignore already includes Maven build patterns');
      return false;
    }

    // Add Maven patterns
    const updatedContent = gitignoreExists
      ? existingContent + '\n' + MAVEN_GITIGNORE_PATTERNS
      : MAVEN_GITIGNORE_PATTERNS.trim() + '\n';

    await writeFile(gitignorePath, updatedContent, 'utf-8');

    if (gitignoreExists) {
      logger.log('✓ Updated .gitignore with Maven build patterns');
    } else {
      logger.log('✓ Created .gitignore with Maven build patterns');
    }

    return true;
  } catch (error) {
    logger.error(`Failed to update .gitignore: ${error.message}`);
    return false;
  }
}

/**
 * Check if project is a Maven project
 * @param {string} workspacePath - Path to repository workspace
 * @returns {Promise<boolean>} True if pom.xml exists
 */
export async function isMavenProject(workspacePath) {
  try {
    const pomPath = join(workspacePath, 'pom.xml');
    await access(pomPath);
    return true;
  } catch {
    return false;
  }
}

